version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00" # After github.com/zonedb/zonedb
    open-pull-requests-limit: 10
