name: Dependabot

on:
  pull_request:

jobs:
  go:
    name: Check Dependabot Go updates
    if: github.event.pull_request.sender.login == 'dependabot-bot'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DOMAINRBOT_RW_GITHUB_ACCESS_TOKEN }}
          ref: ${{ github.head_ref }} # Ensures we check out the branch, not the PR ref
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1

      - name: Download Go modules
        run: |
          go mod tidy
          go test -i -mod=readonly -race ./...

      - name: Verify repo is unchanged
        run: git diff --exit-code HEAD

      - name: Create fixup commit
        if: failure()
        run: |
          git config --global user.email robot@domainr.com
          git config --global user.name domainrbot
          git add go.mod go.sum
          git commit -m "go.{mod,sum}: fixup commit for Dependabot"
          git push origin -u HEAD
